### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by drewwells** [jdrouet/pcloud#29]
Some basic usage and/or install steps would be helpful. Considering buying extra +2tb lifetime subscription based on this project. pCloud should sponsor you!

**Comment by jdrouet** [comment]
Thanks @drewwells!
I'll try to document it. For now, I personally only use the cli. The fuse implementation is not yet stable.
What would you like to see first?

**Comment by drewwells** [comment]
cli is most important to me. I can deal with gui on os x but headless cli on nix is what I’m most in need of.

**Comment by jdrouet** [comment]
@drewwells would that be enough? https://github.com/jdrouet/pcloud/tree/main/cli
I'm preparing a build, going to upload the binaries in the following days
